# Generated by Django 2.1.3 on 2018-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_auto_20181128_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='path',
            field=models.TextField(max_length=255, verbose_name='path'),
        ),
    ]
